server:
  port: 8084
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/qing?characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  # mapper????
  mapper-locations: classpath:mapper/*.xml
swagger:
  enable: true
